# Generated by Django 3.2.3 on 2021-09-10 11:37

from django.db import migrations
from django.db import transaction
import datetime

def seed_data(apps, schema_editor):
    Patient = apps.get_model('clinic', 'Patient')
    Doctor = apps.get_model('clinic', 'Clinician')
    Appointment = apps.get_model('clinic', 'Appointment')
    Visit = apps.get_model('clinic', 'Visit')
    Bill = apps.get_model('clinic', 'Bill')
    patients = [
        Patient(first_name="Harry", last_name="Winks", gender="male", is_registered=True, cellphone_1="0543987867", date_of_birth="1997-12-12"),
        Patient(first_name="Clementine", last_name="Forson", gender="female", is_registered=True, cellphone_1="0543933867", date_of_birth="1987-10-12"),
        Patient(first_name="Ama", last_name="Winston", gender="female", is_registered=False, cellphone_1="0543987889", date_of_birth="1997-01-04"),
        Patient(first_name="James", last_name="Carson", gender="other", is_registered=False, cellphone_1="0543956867", date_of_birth="1980-06-21"),
    ]

    doctors = [
        Doctor(first_name="Edin", last_name="Cole", gender="male", category="doctor", email="edincole@mail.com"),
        Doctor(first_name="Elsie", last_name="Amankwa", gender="female", category="screener", email="dramankwa@mail.com"),
    ]

    appointments = [
        Appointment(patient=patients[0], doctor=doctors[0], start_time=datetime.time(hour=12, minute=40, second=0), end_time=datetime.time(hour=13, minute=40, second=0), date=datetime.date(year=2020, month=9, day=15), status="booked"),
        Appointment(patient=patients[1], doctor=doctors[1], start_time=datetime.time(hour=8, minute=0, second=0), end_time=datetime.time(hour=9, minute=40, second=0), date=datetime.date(year=2020, month=9, day=15), status="honoured"),
        Appointment(patient=patients[2], doctor=doctors[0], start_time=datetime.time(hour=12, minute=00, second=0), end_time=datetime.time(hour=12, minute=40, second=0), date=datetime.date(year=2021, month=12, day=15), status="cancelled"),
        Appointment(patient=patients[3], doctor=doctors[1], start_time=datetime.time(hour=14, minute=00, second=0), end_time=datetime.time(hour=15, minute=00, second=0), date=datetime.date(year=2020, month=5, day=3), status="pending"),
        Appointment(patient=patients[0], doctor=doctors[0], start_time=datetime.time(hour=9, minute=20, second=0), end_time=datetime.time(hour=11, minute=00, second=0), date=datetime.date(year=2021, month=3, day=9), status="confirmed"),
    ]

    visits = [
        Visit(patient=patients[1], doctor=doctors[1], start_time=datetime.time(hour=8, minute=0, second=0), date=datetime.date(year=2020, month=9, day=15), status="examined"),
    ]

    bills = [
        Bill(status="registered", amount="2000", visit=visits[0])
    ]

    with transaction.atomic():
        for patient in patients:
            patient.save()
        for doctor in doctors:
            doctor.save()
        for appointment in appointments:
            appointment.save()
        for visit in visits:
            visit.save()
        for bill in bills:
            bill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(seed_data),
    ]
